services:
  db:
    image: mongo:7
    ports:
      - 27017:27017
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - "db_data:/data/db"
      - "db_config:/data/configdb"
      - ./mongo/admin.user.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  db_data:
  db_config: